name: toast_kit
description: >-
  A production-grade Flutter SDK for in-app toast notifications.
version: 2.3.0
homepage: https://github.com/yasersabri580-oss/toast-kit
repository: https://github.com/yasersabri580-oss/toast-kit
issue_tracker: https://github.com/yasersabri580-oss/toast-kit/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
