import 'builder_models.dart';

// =============================================================================
// Full Code Generator
//
// Generates complete, production-ready Dart code from the builder
// configuration. The output includes imports, channel definitions,
// variant registration, rule setup, and usage examples.
// =============================================================================

/// Generates complete Dart code from the builder configuration.
class FullCodeGenerator {
  FullCodeGenerator._();

  /// Generate the complete code for all configured channels, variants,
  /// rules, and example usage.
  static String generate(BuilderConfiguration config) {
    final buf = StringBuffer();

    buf.writeln("// =============================================================");
    buf.writeln("// Generated by ToastKit Builder");
    buf.writeln("// =============================================================");
    buf.writeln();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln("import 'package:toast_kit/toast_kit.dart';");
    buf.writeln();

    // ── Channel Definitions ──
    if (config.channels.isNotEmpty) {
      buf.writeln('// ─── Channel Definitions ─────────────────────────────────');
      buf.writeln();
      for (final ch in config.channels) {
        _writeChannelDefinition(buf, ch);
        buf.writeln();
      }
    }

    // ── Initialization ──
    buf.writeln('// ─── Initialization ──────────────────────────────────────');
    buf.writeln();
    _writeInitialization(buf, config);
    buf.writeln();

    // ── Variant Registration ──
    if (config.registeredVariantNames.isNotEmpty) {
      buf.writeln('// ─── Custom Variant Registration ─────────────────────────');
      buf.writeln();
      _writeVariantRegistration(buf, config);
      buf.writeln();
    }

    // ── Channel Registration with Config ──
    if (config.channelConfigs.isNotEmpty) {
      buf.writeln('// ─── Channel Configuration ───────────────────────────────');
      buf.writeln();
      _writeChannelConfigs(buf, config);
      buf.writeln();
    }

    // ── Config-Based Rules ──
    if (config.ruleConfigs.isNotEmpty) {
      buf.writeln('// ─── Config-Based Rules ──────────────────────────────────');
      buf.writeln();
      _writeRuleConfigs(buf, config);
      buf.writeln();
    }

    // ── Custom Rules ──
    if (config.customRules.isNotEmpty) {
      buf.writeln('// ─── Custom Rules ────────────────────────────────────────');
      buf.writeln();
      _writeCustomRules(buf, config);
      buf.writeln();
    }

    // ── Usage Examples ──
    buf.writeln('// ─── Usage Examples ──────────────────────────────────────');
    buf.writeln();
    _writeUsageExamples(buf, config);

    return buf.toString().trimRight();
  }

  static void _writeChannelDefinition(StringBuffer buf, ChannelModel ch) {
    buf.writeln("/// ${ch.label} channel.");
    buf.writeln("const ${_channelVarName(ch.id)} = ToastChannel(");
    buf.writeln("  id: '${ch.id}',");
    buf.writeln("  label: '${ch.label}',");
    if (ch.maxVisible != null) {
      buf.writeln("  maxVisible: ${ch.maxVisible},");
    }
    if (ch.defaultPriority != null) {
      buf.writeln("  defaultPriority: ToastPriority.${ch.defaultPriority!.name},");
    }
    if (ch.defaultPosition != null) {
      buf.writeln("  defaultPosition: ToastPosition.${ch.defaultPosition!.name},");
    }
    if (ch.defaultDuration != null) {
      buf.writeln("  defaultDuration: Duration(milliseconds: ${ch.defaultDuration!.inMilliseconds}),");
    }
    if (ch.defaultAnimation != null) {
      buf.writeln("  defaultAnimation: ToastAnimationType.${ch.defaultAnimation!.name},");
    }
    if (ch.defaultVariant != null) {
      buf.writeln("  defaultVariant: ToastVariant.${ch.defaultVariant!.name},");
    }
    if (ch.customVariantName != null && ch.customVariantName!.isNotEmpty) {
      buf.writeln("  customVariantName: '${ch.customVariantName}',");
    }
    if (!ch.enabled) {
      buf.writeln("  enabled: false,");
    }
    buf.writeln(");");
  }

  static void _writeInitialization(StringBuffer buf, BuilderConfiguration config) {
    buf.writeln("void initToastKit(GlobalKey<NavigatorState> navigatorKey) {");
    buf.writeln("  ToastKit.init(");
    buf.writeln("    navigatorKey: navigatorKey,");
    if (config.channels.isNotEmpty) {
      buf.writeln("    channels: [");
      for (final ch in config.channels) {
        buf.writeln("      ${_channelVarName(ch.id)},");
      }
      buf.writeln("    ],");
    }
    buf.writeln("  );");

    // Register channel configs
    for (final entry in config.channelConfigs.entries) {
      final cc = entry.value;
      final hasNonDefault = cc.maxVisible != null ||
          cc.duration != null ||
          cc.interruptCurrent ||
          cc.enableDeduplication ||
          cc.enableThrottling;
      if (hasNonDefault) {
        buf.writeln();
        buf.writeln("  // Configure ${entry.key} channel policies");
        buf.writeln("  ToastKit.registerChannel(");
        buf.writeln("    ${_channelVarName(entry.key)},");
        buf.writeln("    config: const ChannelConfig(");
        if (cc.maxVisible != null) {
          buf.writeln("      maxVisible: ${cc.maxVisible},");
        }
        if (cc.duration != null) {
          buf.writeln("      duration: Duration(milliseconds: ${cc.duration!.inMilliseconds}),");
        }
        if (cc.interruptCurrent) {
          buf.writeln("      interruptCurrent: true,");
        }
        if (cc.enableDeduplication) {
          buf.writeln("      enableDeduplication: true,");
          buf.writeln("      deduplicationWindow: Duration(seconds: ${cc.deduplicationWindowSec}),");
        }
        if (cc.enableThrottling) {
          buf.writeln("      enableThrottling: true,");
          buf.writeln("      throttleInterval: Duration(milliseconds: ${cc.throttleIntervalMs}),");
        }
        buf.writeln("    ),");
        buf.writeln("  );");
      }
    }

    // Register variants
    if (config.registeredVariantNames.isNotEmpty) {
      buf.writeln();
      buf.writeln("  // Register custom variants");
      for (final name in config.registeredVariantNames) {
        final className = _variantClassName(name);
        buf.writeln("  ToastKit.registerVariant($className());");
      }
    }

    // Configure rules
    if (config.ruleConfigs.isNotEmpty || config.customRules.isNotEmpty) {
      buf.writeln();
      buf.writeln("  // Set up rules");
      buf.writeln("  _configureRules();");
    }

    buf.writeln("}");
  }

  static void _writeVariantRegistration(StringBuffer buf, BuilderConfiguration config) {
    buf.writeln("// Custom variant classes — implement these in your project:");
    for (final name in config.registeredVariantNames) {
      final className = _variantClassName(name);
      buf.writeln("//");
      buf.writeln("// class $className extends CustomToastVariantBuilder {");
      buf.writeln("//   @override");
      buf.writeln("//   String get name => '$name';");
      buf.writeln("//");
      buf.writeln("//   @override");
      buf.writeln("//   Widget build(BuildContext context, ToastEvent event,");
      buf.writeln("//       ToastController controller) {");
      buf.writeln("//     // Your custom toast UI here");
      buf.writeln("//     return Container(/* ... */);");
      buf.writeln("//   }");
      buf.writeln("// }");
      buf.writeln();
    }
  }

  static void _writeChannelConfigs(StringBuffer buf, BuilderConfiguration config) {
    buf.writeln("// Channel-specific configs are applied during initialization.");
    buf.writeln("// See the initToastKit() function above.");
  }

  static void _writeRuleConfigs(StringBuffer buf, BuilderConfiguration config) {
    buf.writeln("void _configureRules() {");
    for (final rule in config.ruleConfigs) {
      buf.writeln("  // Config-based rule on '${rule.channelId}' channel");
      buf.writeln("  ToastKit.configureRule(");
      buf.writeln("    '${rule.channelId}',");
      buf.writeln("    const RuleConfig(");
      buf.writeln("      errorThreshold: ${rule.errorThreshold},");
      buf.writeln("      deduplicateWindow: Duration(seconds: ${rule.deduplicateWindowSec}),");
      buf.writeln("      maxTriggers: ${rule.maxTriggers},");
      buf.writeln("    ),");
      buf.writeln("  );");
      buf.writeln();
    }

    // Also include custom rules in the same function
    for (final rule in config.customRules) {
      _writeCustomRule(buf, rule);
      buf.writeln();
    }

    buf.writeln("}");
  }

  static void _writeCustomRules(StringBuffer buf, BuilderConfiguration config) {
    if (config.ruleConfigs.isEmpty) {
      // If no config rules, we need to create the function here
      buf.writeln("void _configureRules() {");
      for (final rule in config.customRules) {
        _writeCustomRule(buf, rule);
        buf.writeln();
      }
      buf.writeln("}");
    } else {
      buf.writeln("// Custom rules are included in _configureRules() above.");
    }
  }

  static void _writeCustomRule(StringBuffer buf, CustomRuleModel rule) {
    buf.writeln("  // Custom rule: ${rule.id}");
    buf.writeln("  ToastKit.addRule(ToastRule(");
    buf.writeln("    id: '${rule.id}',");
    buf.writeln("    channel: '${rule.channelId}',");
    if (rule.maxTriggers > 0) {
      buf.writeln("    maxTriggers: ${rule.maxTriggers},");
    }
    if (rule.deduplicateWindowSec != null) {
      buf.writeln("    deduplicateWindow: Duration(seconds: ${rule.deduplicateWindowSec}),");
    }

    // Condition
    buf.writeln("    condition: (stats, event) {");
    switch (rule.conditionType) {
      case RuleConditionType.errorCountGte:
        buf.writeln("      return stats.errorCount >= ${rule.conditionThreshold};");
        break;
      case RuleConditionType.totalCountGte:
        buf.writeln("      return stats.totalCount >= ${rule.conditionThreshold};");
        break;
      case RuleConditionType.errorsInWindowGte:
        buf.writeln("      return stats.errorsInWindow(const Duration(seconds: 30)) >= ${rule.conditionThreshold};");
        break;
      case RuleConditionType.warningCountGte:
        buf.writeln("      return stats.warningCount >= ${rule.conditionThreshold};");
        break;
    }
    buf.writeln("    },");

    // Action
    buf.writeln("    action: (context) {");
    final toastMethod = _toastMethodForActionType(rule.actionType);
    if (rule.actionType == RuleActionType.showActionToast) {
      buf.writeln("      ToastKit.show(ToastEvent.info(");
      buf.writeln("        message: '${_escapeString(rule.actionMessage)}',");
      if (rule.actionTitle != null && rule.actionTitle!.isNotEmpty) {
        buf.writeln("        title: '${_escapeString(rule.actionTitle!)}',");
      }
      buf.writeln("        variant: ToastVariant.action,");
      if (rule.persistent) buf.writeln("        persistent: true,");
      if (!rule.dismissible) buf.writeln("        dismissible: false,");
      buf.writeln("        channel: '${rule.channelId}',");
      buf.writeln("        actions: [");
      buf.writeln("          ToastAction(");
      buf.writeln("            label: 'Action',");
      buf.writeln("            onPressed: () {");
      buf.writeln("              // Handle action");
      buf.writeln("            },");
      buf.writeln("          ),");
      buf.writeln("        ],");
      buf.writeln("      ));");
    } else {
      buf.writeln("      ToastKit.$toastMethod(");
      buf.writeln("        '${_escapeString(rule.actionMessage)}',");
      if (rule.actionTitle != null && rule.actionTitle!.isNotEmpty) {
        buf.writeln("        title: '${_escapeString(rule.actionTitle!)}',");
      }
      buf.writeln("        channel: '${rule.channelId}',");
      buf.writeln("      );");
    }
    buf.writeln("    },");
    buf.writeln("  ));");
  }

  static void _writeUsageExamples(StringBuffer buf, BuilderConfiguration config) {
    if (config.channels.isEmpty) {
      buf.writeln("// Show a toast on the default channel");
      buf.writeln("ToastKit.success('Operation completed!');");
      buf.writeln("ToastKit.error('Something went wrong.');");
      buf.writeln("ToastKit.info('New update available.');");
      return;
    }

    for (final ch in config.channels) {
      buf.writeln("// Show toasts on the '${ch.id}' channel");
      buf.writeln("ToastKit.success('Success!', channel: '${ch.id}');");
      buf.writeln("ToastKit.error('Error occurred.', channel: '${ch.id}');");
      buf.writeln();
      buf.writeln("// Using the fluent channel API");
      buf.writeln("ToastKit.channel('${ch.id}').success('Done!');");
      buf.writeln("ToastKit.channel('${ch.id}').error('Failed.');");
      buf.writeln();
    }

    buf.writeln("// Progress / loading toast");
    buf.writeln("final ctrl = ToastKit.showLoading('Processing…');");
    buf.writeln("// Update progress:");
    buf.writeln("// ctrl.update(message: 'Processing… 50%');");
    buf.writeln("// ctrl.progress.value = 0.5;");
    buf.writeln("// Complete:");
    buf.writeln("// ctrl.success('Done!');");
    buf.writeln("// Or fail:");
    buf.writeln("// ctrl.error('Failed.');");
  }

  // ── Helpers ──

  /// Convert a channel id like 'my_channel' to a camelCase variable name.
  static String _channelVarName(String id) {
    final parts = id.split(RegExp(r'[_\-\s]+'));
    if (parts.isEmpty) return 'channel';
    final first = parts.first.toLowerCase();
    final rest = parts.skip(1).map((p) {
      if (p.isEmpty) return '';
      return p[0].toUpperCase() + p.substring(1).toLowerCase();
    }).join();
    return '${first}${rest}Channel';
  }

  /// Convert a variant name like 'payment_success' to PascalCase class name.
  static String _variantClassName(String name) {
    final parts = name.split(RegExp(r'[_\-\s]+'));
    return parts.map((p) {
      if (p.isEmpty) return '';
      return p[0].toUpperCase() + p.substring(1).toLowerCase();
    }).join() + 'Variant';
  }

  /// Get the ToastKit convenience method name for a rule action type.
  static String _toastMethodForActionType(RuleActionType type) {
    switch (type) {
      case RuleActionType.showInfoToast:
        return 'info';
      case RuleActionType.showWarningToast:
        return 'warning';
      case RuleActionType.showErrorToast:
        return 'error';
      case RuleActionType.showActionToast:
        return 'info';
    }
  }

  /// Escape single quotes in a string for Dart code.
  static String _escapeString(String s) {
    return s.replaceAll("'", "\\'");
  }
}
